---
# Uninstall Raspbian bloat
- name: Remove raspbian bloat
  apt:
    name: "{{ packages }}"
    state: absent
    autoremove: true
  vars:
    packages:
      - wolfram-engine
      - libreoffice*
      - scratch
      - minecraft-pi
      - python-minecraftpi 
      - python3-minecraftpi
      - sonic-pi
      - dillo
      - gpicview
      - penguinspuzzle
  tags: ['software', 'cleanup']

# Install required software
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600
  tags: ['software']

- name: Install basic software environment
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - vim
      - git
      - python3-pip
      - ufw
  tags: ['software']

- name: Install additional software
  apt:
    name: "{{ myconfig.extra_software }}"
    state: present
  when: "'extra_software' in myconfig and myconfig.extra_software is defined"
  tags: ['software']
